name: Deploy Docs

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          # cache: "npm"
          # cache-dependency-path: "**/package-lock.json"

      - run: npm ci
      - run: npm run build

      - name: Deploy storybook to GitHub Pages
        working-directory: packages/docs
        run: npm run build-storybook && npm run deploy-storybook -- --ci --existing-output-dir=storybook-static
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write
  pages: write
  id-token: write